# config/routes.yaml

# the "app_lucky_number" route name is not important yet
iut_test_technique:
    path: /IUT/accueil
    controller: App\Controller\IUTinfos::News

iut_dept:
    path: /IUT/departements
    controller: App\Controller\IUTinfos::Depts