# config/routes.yaml

iut_test_technique:
    path: /
    controller: App\Controller\IUTinfos::News

iut_dept:
    path: /departements
    controller: App\Controller\IUTinfos::Depts

iut_actu:
    path: /actualites
    controller: App\Controller\IUTinfos::Actu